// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: box.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBox = `-- name: CreateBox :one
INSERT INTO box (
    fingerprint_id,
    container_id,
    status,
    last_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING fingerprint_id, container_id, status, last_active
`

type CreateBoxParams struct {
	FingerprintID uuid.UUID        `json:"fingerprint_id"`
	ContainerID   string           `json:"container_id"`
	Status        string           `json:"status"`
	LastActive    pgtype.Timestamp `json:"last_active"`
}

func (q *Queries) CreateBox(ctx context.Context, arg CreateBoxParams) (Box, error) {
	row := q.db.QueryRow(ctx, createBox,
		arg.FingerprintID,
		arg.ContainerID,
		arg.Status,
		arg.LastActive,
	)
	var i Box
	err := row.Scan(
		&i.FingerprintID,
		&i.ContainerID,
		&i.Status,
		&i.LastActive,
	)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM box
WHERE fingerprint_id = $1
`

func (q *Queries) DeleteBox(ctx context.Context, fingerprintID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBox, fingerprintID)
	return err
}

const getBoxByContainerID = `-- name: GetBoxByContainerID :one
SELECT fingerprint_id, container_id, status, last_active FROM box
WHERE container_id = $1 LIMIT 1
`

func (q *Queries) GetBoxByContainerID(ctx context.Context, containerID string) (Box, error) {
	row := q.db.QueryRow(ctx, getBoxByContainerID, containerID)
	var i Box
	err := row.Scan(
		&i.FingerprintID,
		&i.ContainerID,
		&i.Status,
		&i.LastActive,
	)
	return i, err
}

const getBoxByFingerprint = `-- name: GetBoxByFingerprint :one
SELECT fingerprint_id, container_id, status, last_active FROM box
WHERE fingerprint_id = $1 LIMIT 1
`

func (q *Queries) GetBoxByFingerprint(ctx context.Context, fingerprintID uuid.UUID) (Box, error) {
	row := q.db.QueryRow(ctx, getBoxByFingerprint, fingerprintID)
	var i Box
	err := row.Scan(
		&i.FingerprintID,
		&i.ContainerID,
		&i.Status,
		&i.LastActive,
	)
	return i, err
}

const getExpiredBoxes = `-- name: GetExpiredBoxes :many
SELECT fingerprint_id, container_id, status, last_active FROM box
WHERE last_active < $1
`

// Used by the 24h cleanup worker
func (q *Queries) GetExpiredBoxes(ctx context.Context, lastActive pgtype.Timestamp) ([]Box, error) {
	rows, err := q.db.Query(ctx, getExpiredBoxes, lastActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.FingerprintID,
			&i.ContainerID,
			&i.Status,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxesByStatus = `-- name: ListBoxesByStatus :many
SELECT fingerprint_id, container_id, status, last_active FROM box
WHERE status = $1
`

func (q *Queries) ListBoxesByStatus(ctx context.Context, status string) ([]Box, error) {
	rows, err := q.db.Query(ctx, listBoxesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.FingerprintID,
			&i.ContainerID,
			&i.Status,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchBox = `-- name: TouchBox :exec
UPDATE box
SET last_active = $2,
    status = 'active'
WHERE fingerprint_id = $1
`

type TouchBoxParams struct {
	FingerprintID uuid.UUID        `json:"fingerprint_id"`
	LastActive    pgtype.Timestamp `json:"last_active"`
}

// Updates last_active and ensures status is 'active'
func (q *Queries) TouchBox(ctx context.Context, arg TouchBoxParams) error {
	_, err := q.db.Exec(ctx, touchBox, arg.FingerprintID, arg.LastActive)
	return err
}

const updateBoxStatus = `-- name: UpdateBoxStatus :exec
UPDATE box
SET status = $2
WHERE fingerprint_id = $1
`

type UpdateBoxStatusParams struct {
	FingerprintID uuid.UUID `json:"fingerprint_id"`
	Status        string    `json:"status"`
}

func (q *Queries) UpdateBoxStatus(ctx context.Context, arg UpdateBoxStatusParams) error {
	_, err := q.db.Exec(ctx, updateBoxStatus, arg.FingerprintID, arg.Status)
	return err
}
