// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Box struct {
	FingerprintID uuid.UUID        `json:"fingerprint_id"`
	ContainerID   string           `json:"container_id"`
	Status        string           `json:"status"`
	LastActive    pgtype.Timestamp `json:"last_active"`
}
