// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Box struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	FingerprintID string           `db:"fingerprint_id" json:"fingerprint_id"`
	ContainerID   string           `db:"container_id" json:"container_id"`
	Status        string           `db:"status" json:"status"`
	LastActive    pgtype.Timestamp `db:"last_active" json:"last_active"`
}
